### ISSUE TITLE
管理员使用移出功能报错

### ISSUE THREAD

**Issue by xulirong1** [LCTT/LCBot#27]
`An error occurred in <function wxpy_group at 0x0000000003661048>.
   Traceback (most recent call last):
     File "E:\python3\lib\site-packages\wxpy\api\bot.py", line 418, in process
       ret = config.func(msg)
     File "bot.py", line 168, in wxpy_group
       ret_msg = remote_kick(msg)
     File "bot.py", line 96, in remote_kick
       if not from_admin(msg):
     File "bot.py", line 84, in from_admin
       print(admins)
     File "E:\python3\lib\encodings\cp437.py", line 19, in encode
       return codecs.charmap_encode(input,self.errors,encoding_map)[0]
   UnicodeEncodeError: 'charmap' codec can't encode characters in position 10-11: character maps to <undefined>`

**Comment by OSMeteor** [comment]
你应该需要把管理员权限给到机器人
